Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/01/2026
Var
dobro, terca, n : real
Inicio
escreva("digite um número:")
leia(n)
dobro <- n * 2
terca <- n / 3
escreval("O dobro de",n," é",dobro)
escreva("A terça parte de",n," é",terca)

Fimalgoritmo