Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/02/2026
Var
reais, dolares : real


Inicio
escreva("Qual a quantia em Reais:")
leia(reais)
dolares <- reais / 3.45
escreva(dolares:4:2)


Fimalgoritmo