Algoritmo "soma_número"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2026
Var
n1, n2, soma: inteiro


Inicio
escreva("Digite o primeiro número:")
leia(n1)
escreva("Digite o segundo número:")
leia(n2)
soma <- n1 + n2
escreva("A soma dos dois números é:", soma)
Fimalgoritmo